### ISSUE TITLE
Migrating ibm-bas resources off of machine caused configmap to disappear

### ISSUE THREAD

**Issue by grtn316** [Azure/maximo#1]
While setting up node selectors on machine set to isolate workloads and scaling down/up machine counts the operator resources: Red Hat Integration - AMQ Streams (pod: amq-streams-cluster-operator-v1.7.3) unexpectedly lost the following ConfigMap: https://github.com/jboss-container-images/amqstreams-1-openshift-image/blob/dadc1e8f276f3b0c10001f916c48d87c54483f60/operator-metadata/manifests/strimziclusteroperator.configmap.yaml

Issue was found in the events for the pod that was stuck initalizing.

**Comment by ranieuwe** [comment]
#stale closing
