### ISSUE TITLE
Determine MachineSet configuration to support workloads

### ISSUE THREAD

**Issue by grtn316** [Azure/maximo#8]
Determine the desired configuration for MachineSets when deploying the following on OCP:

- IBM Maximo Core Services
- Cloud Pak for Data
- Db2 Warehouse
- Openshift Container Storage

**Should include the following:**

- Sku selection by type (master / worker)
- Minimum # of nodes
- Worker isolation to prevent noisy neighbor from cpu/ram intense workloads
- Node Selector Configuration

**Comment by ranieuwe** [comment]
#stale closing
